/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as TasksTaskIdDetailsRouteImport } from './routes/tasks/$taskId/details'
import { Route as RunsRunIdDetailsRouteImport } from './routes/runs/$runId/details'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const TasksTaskIdDetailsRoute = TasksTaskIdDetailsRouteImport.update({
  id: '/$taskId/details',
  path: '/$taskId/details',
  getParentRoute: () => TasksRoute,
} as any)
const RunsRunIdDetailsRoute = RunsRunIdDetailsRouteImport.update({
  id: '/$runId/details',
  path: '/$runId/details',
  getParentRoute: () => RunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/runs': typeof RunsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/tasks/': typeof TasksIndexRoute
  '/runs/$runId/details': typeof RunsRunIdDetailsRoute
  '/tasks/$taskId/details': typeof TasksTaskIdDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/runs': typeof RunsRouteWithChildren
  '/tasks': typeof TasksIndexRoute
  '/runs/$runId/details': typeof RunsRunIdDetailsRoute
  '/tasks/$taskId/details': typeof TasksTaskIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/runs': typeof RunsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/tasks/': typeof TasksIndexRoute
  '/runs/$runId/details': typeof RunsRunIdDetailsRoute
  '/tasks/$taskId/details': typeof TasksTaskIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/live'
    | '/runs'
    | '/tasks'
    | '/tasks/'
    | '/runs/$runId/details'
    | '/tasks/$taskId/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/live'
    | '/runs'
    | '/tasks'
    | '/runs/$runId/details'
    | '/tasks/$taskId/details'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/live'
    | '/runs'
    | '/tasks'
    | '/tasks/'
    | '/runs/$runId/details'
    | '/tasks/$taskId/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  LiveRoute: typeof LiveRoute
  RunsRoute: typeof RunsRouteWithChildren
  TasksRoute: typeof TasksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$taskId/details': {
      id: '/tasks/$taskId/details'
      path: '/$taskId/details'
      fullPath: '/tasks/$taskId/details'
      preLoaderRoute: typeof TasksTaskIdDetailsRouteImport
      parentRoute: typeof TasksRoute
    }
    '/runs/$runId/details': {
      id: '/runs/$runId/details'
      path: '/$runId/details'
      fullPath: '/runs/$runId/details'
      preLoaderRoute: typeof RunsRunIdDetailsRouteImport
      parentRoute: typeof RunsRoute
    }
  }
}

interface RunsRouteChildren {
  RunsRunIdDetailsRoute: typeof RunsRunIdDetailsRoute
}

const RunsRouteChildren: RunsRouteChildren = {
  RunsRunIdDetailsRoute: RunsRunIdDetailsRoute,
}

const RunsRouteWithChildren = RunsRoute._addFileChildren(RunsRouteChildren)

interface TasksRouteChildren {
  TasksIndexRoute: typeof TasksIndexRoute
  TasksTaskIdDetailsRoute: typeof TasksTaskIdDetailsRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksIndexRoute: TasksIndexRoute,
  TasksTaskIdDetailsRoute: TasksTaskIdDetailsRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  LiveRoute: LiveRoute,
  RunsRoute: RunsRouteWithChildren,
  TasksRoute: TasksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
